[package]
name = "term-wm-pty-engine"
description = "PTY engine for term-wm."
keywords = ["pty", "terminal", "vt100", "conpty", "cross-platform"]
categories = ["emulators", "os", "external-ffi-bindings", "concurrency"]
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
arboard = { workspace = true }
base64 = { workspace = true }
ctrlc = { workspace = true }
libc = { workspace = true }
portable-pty = { workspace = true }
term-wm-events = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
vt100 = { workspace = true }
vte = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
