[package]
name = "term-resize-indicator"
description = "Draws a box with centered dimensions in terminal applications."
keywords = ["terminal", "tui", "ui"]
categories = ["gui", "command-line-interface"]
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

# Internal debug tool; not publishing for now
publish = false

[dependencies]
crossterm = { workspace = true }
ratatui = { workspace = true }
