[package]
name = "term-wm-events"
description = "Input event types (key, mouse, resize, paste) for term-wm."
keywords = ["events", "input", "serde"]
categories = ["gui", "command-line-interface", "rust-patterns"]
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bitcode = { workspace = true, features = ["derive"] }
term-wm-layout-engine = { workspace = true }

[lints]
workspace = true
